apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-client
  namespace: orleans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orleans
      component: client
  template:
    metadata:
      labels:
        app: orleans
        component: client
    spec:
      containers:
      - name: client
        image: wzorgdrager/orleans:0.7
        args:
        - "1"
        - "client"
        - "1"
        - "master.orleans"
        - "1400"
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
